INSERT INTO products (id, name, category, description, price, image) VALUES
(gen_random_uuid(), 'X-Burger', 'LANCHE', 'Um delicioso hambúrguer com queijo', 15.99, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'Batata Frita', 'ACOMPANHAMENTO', 'Batatas fritas crocantes', 8.99, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'Coca-Cola', 'BEBIDA', 'Refrigerante de cola', 5.0, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'Sorvete', 'SOBREMESA', 'Sorvete cremoso de baunilha', 7.5, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'Hambúrguer Vegano', 'LANCHE', 'Hambúrguer sem carne com vegetais', 17.99, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'Nuggets', 'ACOMPANHAMENTO', 'Pequenos pedaços de frango empanados', 10.5, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'Fanta Laranja', 'BEBIDA', 'Refrigerante sabor laranja', 5.0, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'Milkshake', 'SOBREMESA', 'Milkshake de chocolate', 12.0, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'Hot Dog', 'LANCHE', 'Cachorro-quente com salsicha e molho', 12.99, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'Anéis de Cebola', 'ACOMPANHAMENTO', 'Cebolas empanadas e fritas', 7.99, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'Suco de Laranja', 'BEBIDA', 'Suco natural de laranja', 6.5, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'Brownie', 'SOBREMESA', 'Brownie de chocolate com nozes', 8.5, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'X-Salada', 'LANCHE', 'Hambúrguer com salada e queijo', 14.99, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'Queijo Coalho', 'ACOMPANHAMENTO', 'Espeto de queijo coalho grelhado', 9.0, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'Guaraná', 'BEBIDA', 'Refrigerante de guaraná', 5.0, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'Pudim', 'SOBREMESA', 'Pudim de leite condensado', 6.99, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'X-Frango', 'LANCHE', 'Sanduíche de frango grelhado com queijo', 16.99, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'Mandioca Frita', 'ACOMPANHAMENTO', 'Mandiocas fritas crocantes', 7.99, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'Água', 'BEBIDA', 'Água mineral sem gás', 3.0, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'Mousse de Maracujá', 'SOBREMESA', 'Mousse de maracujá', 6.0, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'Cheeseburger', 'LANCHE', 'Hambúrguer com queijo cheddar', 15.49, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'Salada Caesar', 'ACOMPANHAMENTO', 'Salada caesar com frango', 11.0, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'Sprite', 'BEBIDA', 'Refrigerante sabor limão', 5.0, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'Petit Gateau', 'SOBREMESA', 'Bolo de chocolate com recheio quente', 13.5, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'X-Tudo', 'LANCHE', 'Hambúrguer completo com bacon e ovo', 18.99, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'Cebola Empanada', 'ACOMPANHAMENTO', 'Fatias de cebola empanada e frita', 9.5, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'Ice Tea', 'BEBIDA', 'Chá gelado sabor pêssego', 6.5, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'Torta de Limão', 'SOBREMESA', 'Torta de limão com merengue', 10.0, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg'),
(gen_random_uuid(), 'X-Bacon', 'LANCHE', 'Hambúrguer com bacon crocante', 16.99, 'https://blog.letskuk.com.br/wp-content/uploads/2022/10/lanches-gourmet.jpg');
