apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db-deployment
    spec:
      containers:
      - name: postgress
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: lanchonete-fiap-db
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: password
          
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
  selector:
    matchLabels:
      app: db-deployment