apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lanchonete-hpa
spec:
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: lanchonete-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resources
      resources:
        name: cpu
        target:
          type: Utilization
          averegeUtilization: 50
