name: CD -> Deploy to Kubernetes on GKE or EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set deploy target
        id: set-deploy-target
        run: echo "DEPLOY_TARGET=${{ secrets.DEPLOY_TARGET }}" >> $GITHUB_ENV

      - name: Deploy to GKE
        if: env.DEPLOY_TARGET == 'GKE'
        steps:
          - name: Set up Google Cloud SDK
            uses: google-github-actions/setup-gcloud@v1
            with:
              version: 'latest'
              service_account_email: ${{ secrets.GCP_SA_EMAIL }}
              service_account_key: ${{ secrets.GCP_SA_KEY }}
              project_id: ${{ secrets.GCP_PROJECT_ID }}

          - name: Configure kubectl
            run: |
              gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

          - name: Deploy to GKE
            run: |
              kubectl apply -f k8s/

      - name: Deploy to AWS EKS
        if: env.DEPLOY_TARGET == 'EKS'
        steps:
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ secrets.AWS_REGION }}

          - name: Update kubeconfig
            run: |
              aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

          - name: Deploy to EKS
            run: |
              kubectl apply -f k8s/
